
package com.bigarchive.filemanager;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "FileManagerService", targetNamespace = "http://filemanager.zdms_component.mndsc.ru/", wsdlLocation = "file:/home/itiu/work/ba2veda/wsdl/filemanager.wsdl")
public class FileManagerService
    extends Service
{

    private final static URL FILEMANAGERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.bigarchive.filemanager.FileManagerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.bigarchive.filemanager.FileManagerService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/itiu/work/ba2veda/wsdl/filemanager.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/itiu/work/ba2veda/wsdl/filemanager.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        FILEMANAGERSERVICE_WSDL_LOCATION = url;
    }

    public FileManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileManagerService() {
        super(FILEMANAGERSERVICE_WSDL_LOCATION, new QName("http://filemanager.zdms_component.mndsc.ru/", "FileManagerService"));
    }

    /**
     * 
     * @return
     *     returns FileManagerEndpoint
     */
    @WebEndpoint(name = "FileManagerEndpointPort")
    public FileManagerEndpoint getFileManagerEndpointPort() {
        return super.getPort(new QName("http://filemanager.zdms_component.mndsc.ru/", "FileManagerEndpointPort"), FileManagerEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileManagerEndpoint
     */
    @WebEndpoint(name = "FileManagerEndpointPort")
    public FileManagerEndpoint getFileManagerEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://filemanager.zdms_component.mndsc.ru/", "FileManagerEndpointPort"), FileManagerEndpoint.class, features);
    }

}
