
package com.bigarchive.filemanager;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "FileManagerEndpoint", targetNamespace = "http://filemanager.zdms_component.mndsc.ru/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FileManagerEndpoint {


    /**
     * 
     * @param request
     * @return
     *     returns com.bigarchive.filemanager.GetIdsListResponseEnvelope
     */
    @WebMethod
    @WebResult(name = "getIdsListResponseEnvelope", targetNamespace = "http://filemanager.zdms_component.mndsc.ru/", partName = "response")
    public GetIdsListResponseEnvelope getIdsList(
        @WebParam(name = "getIdsListRequestEnvelope", targetNamespace = "http://filemanager.zdms_component.mndsc.ru/", partName = "request")
        GetIdsListRequestEnvelope request);

    /**
     * 
     * @param request
     * @return
     *     returns com.bigarchive.filemanager.GetIndexedFilesResponseEnvelope
     */
    @WebMethod
    @WebResult(name = "getIndexedFilesResponseEnvelope", targetNamespace = "http://filemanager.zdms_component.mndsc.ru/", partName = "response")
    public GetIndexedFilesResponseEnvelope getIndexedFiles(
        @WebParam(name = "getIndexedFilesRequestEnvelope", targetNamespace = "http://filemanager.zdms_component.mndsc.ru/", partName = "request")
        GetIndexedFilesRequestEnvelope request);

    /**
     * 
     * @param request
     * @return
     *     returns com.bigarchive.filemanager.StoreFileResponseEnvelope
     * @throws StoreFileFault
     */
    @WebMethod
    @WebResult(name = "storeFileResponseEnvelope", targetNamespace = "http://filemanager.zdms_component.mndsc.ru/", partName = "response")
    public StoreFileResponseEnvelope storeFile(
        @WebParam(name = "storeFileRequestEnvelope", targetNamespace = "http://filemanager.zdms_component.mndsc.ru/", partName = "request")
        StoreFileRequestEnvelope request)
        throws StoreFileFault
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.bigarchive.filemanager.GetFilesResponseEnvelope
     * @throws GetFilesFault
     */
    @WebMethod
    @WebResult(name = "getFilesResponseEnvelope", targetNamespace = "http://filemanager.zdms_component.mndsc.ru/", partName = "response")
    public GetFilesResponseEnvelope getFiles(
        @WebParam(name = "getFilesRequestEnvelope", targetNamespace = "http://filemanager.zdms_component.mndsc.ru/", partName = "request")
        GetFilesRequestEnvelope request)
        throws GetFilesFault
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.bigarchive.filemanager.GetVersionResponseEnvelope
     */
    @WebMethod
    @WebResult(name = "getVersionResponseEnvelope", targetNamespace = "http://filemanager.zdms_component.mndsc.ru/", partName = "response")
    public GetVersionResponseEnvelope getVersion(
        @WebParam(name = "getVersionRequestEnvelope", targetNamespace = "http://filemanager.zdms_component.mndsc.ru/", partName = "request")
        GetVersionRequestEnvelope request);

}
