
package com.bigarchive.filemanager;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "getFilesFaultEnvelope", targetNamespace = "http://filemanager.zdms_component.mndsc.ru/")
public class GetFilesFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GetFilesFaultEnvelope faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public GetFilesFault(String message, GetFilesFaultEnvelope faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public GetFilesFault(String message, GetFilesFaultEnvelope faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.bigarchive.filemanager.GetFilesFaultEnvelope
     */
    public GetFilesFaultEnvelope getFaultInfo() {
        return faultInfo;
    }

}
