
package magnetico.ws.attachment;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AttachmentService", targetNamespace = "http://attachments.bigarchive.magnetosoft.ru/", wsdlLocation = "file:/home/itiu/work/ba2onto/src/main/wsdl/AttachmentService.wsdl")
public class AttachmentService
    extends Service
{

    private final static URL ATTACHMENTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(magnetico.ws.attachment.AttachmentService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = magnetico.ws.attachment.AttachmentService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/itiu/work/ba2onto/src/main/wsdl/AttachmentService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/itiu/work/ba2onto/src/main/wsdl/AttachmentService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ATTACHMENTSERVICE_WSDL_LOCATION = url;
    }

    public AttachmentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AttachmentService() {
        super(ATTACHMENTSERVICE_WSDL_LOCATION, new QName("http://attachments.bigarchive.magnetosoft.ru/", "AttachmentService"));
    }

    /**
     * 
     * @return
     *     returns AttachmentEndpoint
     */
    @WebEndpoint(name = "AttachmentServiceEndpointPort")
    public AttachmentEndpoint getAttachmentServiceEndpointPort() {
        return super.getPort(new QName("http://attachments.bigarchive.magnetosoft.ru/", "AttachmentServiceEndpointPort"), AttachmentEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AttachmentEndpoint
     */
    @WebEndpoint(name = "AttachmentServiceEndpointPort")
    public AttachmentEndpoint getAttachmentServiceEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://attachments.bigarchive.magnetosoft.ru/", "AttachmentServiceEndpointPort"), AttachmentEndpoint.class, features);
    }

}
