
package ru.magnetosoft.bigarch.wsclient.bl.documentservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DocumentEndpoint", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DocumentEndpoint {


    /**
     * 
     * @param sessionTicketId
     * @return
     *     returns java.lang.String
     * @throws BigArchiveServerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetVersion")
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetVersionResponse")
    public String getVersion(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId)
        throws BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param sessionTicketId
     * @param documentId
     * @return
     *     returns ru.magnetosoft.bigarch.wsclient.bl.documentservice.DocumentType
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocument", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetDocument")
    @ResponseWrapper(localName = "getDocumentResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetDocumentResponse")
    public DocumentType getDocument(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "documentId", targetNamespace = "")
        String documentId)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param document
     * @param sessionTicketId
     * @return
     *     returns java.lang.String
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createDocument", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.CreateDocument")
    @ResponseWrapper(localName = "createDocumentResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.CreateDocumentResponse")
    public String createDocument(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "document", targetNamespace = "")
        DocumentType document)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param objectType
     * @return
     *     returns int
     * @throws BigArchiveServerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "countDocuments", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.CountDocuments")
    @ResponseWrapper(localName = "countDocumentsResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.CountDocumentsResponse")
    public int countDocuments(
        @WebParam(name = "objectType", targetNamespace = "")
        JaxbObjectType objectType)
        throws BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param objectType
     * @return
     *     returns int
     * @throws BigArchiveServerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "countDocumentTemplates", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.CountDocumentTemplates")
    @ResponseWrapper(localName = "countDocumentTemplatesResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.CountDocumentTemplatesResponse")
    public int countDocumentTemplates(
        @WebParam(name = "objectType", targetNamespace = "")
        JaxbObjectType objectType)
        throws BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param quantity
     * @param from
     * @param objectType
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws BigArchiveServerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pageDocuments", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.PageDocuments")
    @ResponseWrapper(localName = "pageDocumentsResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.PageDocumentsResponse")
    public List<String> pageDocuments(
        @WebParam(name = "objectType", targetNamespace = "")
        JaxbObjectType objectType,
        @WebParam(name = "from", targetNamespace = "")
        int from,
        @WebParam(name = "quantity", targetNamespace = "")
        int quantity)
        throws BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param quantity
     * @param from
     * @param objectType
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws BigArchiveServerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pageDocumentTemplates", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.PageDocumentTemplates")
    @ResponseWrapper(localName = "pageDocumentTemplatesResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.PageDocumentTemplatesResponse")
    public List<String> pageDocumentTemplates(
        @WebParam(name = "objectType", targetNamespace = "")
        JaxbObjectType objectType,
        @WebParam(name = "from", targetNamespace = "")
        int from,
        @WebParam(name = "quantity", targetNamespace = "")
        int quantity)
        throws BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param draftId
     * @param sessionTicketId
     * @return
     *     returns ru.magnetosoft.bigarch.wsclient.bl.documentservice.DocumentDraftType
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocumentDraft", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetDocumentDraft")
    @ResponseWrapper(localName = "getDocumentDraftResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetDocumentDraftResponse")
    public DocumentDraftType getDocumentDraft(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "draftId", targetNamespace = "")
        String draftId)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param draftId
     * @param sessionTicketId
     * @return
     *     returns ru.magnetosoft.bigarch.wsclient.bl.documentservice.DocumentTemplateDraftType
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocumentTemplateDraft", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetDocumentTemplateDraft")
    @ResponseWrapper(localName = "getDocumentTemplateDraftResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetDocumentTemplateDraftResponse")
    public DocumentTemplateDraftType getDocumentTemplateDraft(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "draftId", targetNamespace = "")
        String draftId)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param userId
     * @param sessionTicketId
     * @return
     *     returns java.util.List<ru.magnetosoft.bigarch.wsclient.bl.documentservice.DocumentDraftType>
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserDocumentDrafts", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetUserDocumentDrafts")
    @ResponseWrapper(localName = "getUserDocumentDraftsResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetUserDocumentDraftsResponse")
    public List<DocumentDraftType> getUserDocumentDrafts(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "userId", targetNamespace = "")
        String userId)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param draftId
     * @param sessionTicketId
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removeDocumentDraft", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.RemoveDocumentDraft")
    @ResponseWrapper(localName = "removeDocumentDraftResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.RemoveDocumentDraftResponse")
    public void removeDocumentDraft(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "draftId", targetNamespace = "")
        String draftId)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param sessionTicketId
     * @param documentId
     * @return
     *     returns java.lang.String
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createDocumentDraft", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.CreateDocumentDraft")
    @ResponseWrapper(localName = "createDocumentDraftResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.CreateDocumentDraftResponse")
    public String createDocumentDraft(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "documentId", targetNamespace = "")
        String documentId)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param documentTemplateId
     * @param sessionTicketId
     * @return
     *     returns java.lang.String
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createDocumentTemplateDraft", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.CreateDocumentTemplateDraft")
    @ResponseWrapper(localName = "createDocumentTemplateDraftResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.CreateDocumentTemplateDraftResponse")
    public String createDocumentTemplateDraft(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "documentTemplateId", targetNamespace = "")
        String documentTemplateId)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param sessionTicketId
     * @param documentId
     * @return
     *     returns ru.magnetosoft.bigarch.wsclient.bl.documentservice.JaxbDocumentValidationResult
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "commitDocument", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.CommitDocument")
    @ResponseWrapper(localName = "commitDocumentResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.CommitDocumentResponse")
    public JaxbDocumentValidationResult commitDocument(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "documentId", targetNamespace = "")
        String documentId)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param document
     * @param sessionTicketId
     * @return
     *     returns java.lang.String
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createDocumentWithDraft", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.CreateDocumentWithDraft")
    @ResponseWrapper(localName = "createDocumentWithDraftResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.CreateDocumentWithDraftResponse")
    public String createDocumentWithDraft(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "document", targetNamespace = "")
        DocumentType document)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param document
     * @param sessionTicketId
     * @return
     *     returns java.lang.String
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createDocumentBatch", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.CreateDocumentBatch")
    @ResponseWrapper(localName = "createDocumentBatchResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.CreateDocumentBatchResponse")
    public String createDocumentBatch(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "document", targetNamespace = "")
        DocumentType document)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param draft
     * @param sessionTicketId
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateDocumentDraft", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.UpdateDocumentDraft")
    @ResponseWrapper(localName = "updateDocumentDraftResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.UpdateDocumentDraftResponse")
    public void updateDocumentDraft(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "draft", targetNamespace = "")
        DocumentDraftType draft)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param draft
     * @param sessionTicketId
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateDocumentTemplateDraft", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.UpdateDocumentTemplateDraft")
    @ResponseWrapper(localName = "updateDocumentTemplateDraftResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.UpdateDocumentTemplateDraftResponse")
    public void updateDocumentTemplateDraft(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "draft", targetNamespace = "")
        DocumentTemplateDraftType draft)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param sessionTicketId
     * @param documentId
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removeDocument", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.RemoveDocument")
    @ResponseWrapper(localName = "removeDocumentResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.RemoveDocumentResponse")
    public void removeDocument(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "documentId", targetNamespace = "")
        String documentId)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param documentId
     * @return
     *     returns java.lang.String
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocumentXml", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetDocumentXml")
    @ResponseWrapper(localName = "getDocumentXmlResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetDocumentXmlResponse")
    public String getDocumentXml(
        @WebParam(name = "documentId", targetNamespace = "")
        String documentId)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param documentTemplateId
     * @return
     *     returns java.lang.String
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocumentTemplateXml", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetDocumentTemplateXml")
    @ResponseWrapper(localName = "getDocumentTemplateXmlResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetDocumentTemplateXmlResponse")
    public String getDocumentTemplateXml(
        @WebParam(name = "documentTemplateId", targetNamespace = "")
        String documentTemplateId)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param date
     * @param sessionTicketId
     * @param documentId
     * @return
     *     returns ru.magnetosoft.bigarch.wsclient.bl.documentservice.DocumentType
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocumentByDate", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetDocumentByDate")
    @ResponseWrapper(localName = "getDocumentByDateResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetDocumentByDateResponse")
    public DocumentType getDocumentByDate(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "documentId", targetNamespace = "")
        String documentId,
        @WebParam(name = "date", targetNamespace = "")
        XMLGregorianCalendar date)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param newDocumentTemplate
     * @param sessionTicketId
     * @return
     *     returns java.lang.String
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createDocumentTemplateWithDraft", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.CreateDocumentTemplateWithDraft")
    @ResponseWrapper(localName = "createDocumentTemplateWithDraftResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.CreateDocumentTemplateWithDraftResponse")
    public String createDocumentTemplateWithDraft(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "newDocumentTemplate", targetNamespace = "")
        DocumentTemplateType newDocumentTemplate)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param documentTemplate
     * @param sessionTicketId
     * @return
     *     returns java.lang.String
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "commitDocumentTemplate", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.CommitDocumentTemplate")
    @ResponseWrapper(localName = "commitDocumentTemplateResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.CommitDocumentTemplateResponse")
    public String commitDocumentTemplate(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "documentTemplate", targetNamespace = "")
        String documentTemplate)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param documentTemplateId
     * @param sessionTicketId
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removeDocumentTemplate", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.RemoveDocumentTemplate")
    @ResponseWrapper(localName = "removeDocumentTemplateResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.RemoveDocumentTemplateResponse")
    public void removeDocumentTemplate(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "documentTemplateId", targetNamespace = "")
        String documentTemplateId)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param contexDocumentId
     * @param documentTemplateId
     * @param sessionTicketId
     * @return
     *     returns ru.magnetosoft.bigarch.wsclient.bl.documentservice.DocumentTemplateType
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocumentTemplate", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetDocumentTemplate")
    @ResponseWrapper(localName = "getDocumentTemplateResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetDocumentTemplateResponse")
    public DocumentTemplateType getDocumentTemplate(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "contexDocumentId", targetNamespace = "")
        String contexDocumentId,
        @WebParam(name = "documentTemplateId", targetNamespace = "")
        String documentTemplateId)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param contexDocumentId
     * @param documentTemplateId
     * @param date
     * @param sessionTicketId
     * @return
     *     returns ru.magnetosoft.bigarch.wsclient.bl.documentservice.DocumentTemplateType
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocumentTemplateByDate", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetDocumentTemplateByDate")
    @ResponseWrapper(localName = "getDocumentTemplateByDateResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetDocumentTemplateByDateResponse")
    public DocumentTemplateType getDocumentTemplateByDate(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "contexDocumentId", targetNamespace = "")
        String contexDocumentId,
        @WebParam(name = "documentTemplateId", targetNamespace = "")
        String documentTemplateId,
        @WebParam(name = "date", targetNamespace = "")
        XMLGregorianCalendar date)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param withAttributes
     * @param forDocumentCreating
     * @param sessionTicketId
     * @param objectType
     * @return
     *     returns java.util.List<ru.magnetosoft.bigarch.wsclient.bl.documentservice.DocumentTemplateType>
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocumentTemplates", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetDocumentTemplates")
    @ResponseWrapper(localName = "getDocumentTemplatesResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetDocumentTemplatesResponse")
    public List<DocumentTemplateType> getDocumentTemplates(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "objectType", targetNamespace = "")
        JaxbObjectType objectType,
        @WebParam(name = "withAttributes", targetNamespace = "")
        boolean withAttributes,
        @WebParam(name = "forDocumentCreating", targetNamespace = "")
        boolean forDocumentCreating)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param computationals
     * @param draftId
     * @param sessionTicketId
     * @return
     *     returns java.util.List<ru.magnetosoft.bigarch.wsclient.bl.documentservice.AttributeType>
     * @throws BigArchiveServerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComputationalAttributes", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetComputationalAttributes")
    @ResponseWrapper(localName = "getComputationalAttributesResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetComputationalAttributesResponse")
    public List<AttributeType> getComputationalAttributes(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "draftId", targetNamespace = "")
        String draftId,
        @WebParam(name = "computationals", targetNamespace = "")
        List<AttributeType> computationals)
        throws BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param sessionTicketId
     * @param documentId
     * @return
     *     returns boolean
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isInDocflow", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.IsInDocflow")
    @ResponseWrapper(localName = "isInDocflowResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.IsInDocflowResponse")
    public boolean isInDocflow(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "documentId", targetNamespace = "")
        String documentId)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param sessionTicketId
     * @param documentId
     * @return
     *     returns ru.magnetosoft.bigarch.wsclient.bl.documentservice.DocumentType
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocumentWithTemplate", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetDocumentWithTemplate")
    @ResponseWrapper(localName = "getDocumentWithTemplateResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetDocumentWithTemplateResponse")
    public DocumentType getDocumentWithTemplate(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "documentId", targetNamespace = "")
        String documentId)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param date
     * @param sessionTicketId
     * @param documentId
     * @return
     *     returns ru.magnetosoft.bigarch.wsclient.bl.documentservice.DocumentType
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocumentWithTemplateByDate", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetDocumentWithTemplateByDate")
    @ResponseWrapper(localName = "getDocumentWithTemplateByDateResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.GetDocumentWithTemplateByDateResponse")
    public DocumentType getDocumentWithTemplateByDate(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "documentId", targetNamespace = "")
        String documentId,
        @WebParam(name = "date", targetNamespace = "")
        XMLGregorianCalendar date)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param newDocumentTemplate
     * @param sessionTicketId
     * @return
     *     returns java.lang.String
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createDocumentTemplate", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.CreateDocumentTemplate")
    @ResponseWrapper(localName = "createDocumentTemplateResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.CreateDocumentTemplateResponse")
    public String createDocumentTemplate(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "newDocumentTemplate", targetNamespace = "")
        DocumentTemplateType newDocumentTemplate)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param document
     * @param sessionTicketId
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateDocument", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.UpdateDocument")
    @ResponseWrapper(localName = "updateDocumentResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.UpdateDocumentResponse")
    public void updateDocument(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "document", targetNamespace = "")
        DocumentType document)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param documentTemplate
     * @param sessionTicketId
     * @throws BigArchiveServerException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateDocumentTemplate", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.UpdateDocumentTemplate")
    @ResponseWrapper(localName = "updateDocumentTemplateResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.UpdateDocumentTemplateResponse")
    public void updateDocumentTemplate(
        @WebParam(name = "sessionTicketId", targetNamespace = "")
        String sessionTicketId,
        @WebParam(name = "documentTemplate", targetNamespace = "")
        DocumentTemplateType documentTemplate)
        throws AccessDeniedException_Exception, BigArchiveServerException_Exception
    ;

    /**
     * 
     * @param templateId
     * @return
     *     returns int
     * @throws BigArchiveServerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "countDocumentsByTemplateId", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.CountDocumentsByTemplateId")
    @ResponseWrapper(localName = "countDocumentsByTemplateIdResponse", targetNamespace = "http://documents.bigarchive.magnetosoft.ru/", className = "ru.magnetosoft.bigarch.wsclient.bl.documentservice.CountDocumentsByTemplateIdResponse")
    public int countDocumentsByTemplateId(
        @WebParam(name = "templateId", targetNamespace = "")
        String templateId)
        throws BigArchiveServerException_Exception
    ;

}
