
package magnetico.ws.search;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SearchService", targetNamespace = "http://search.bigarchive.magnetosoft.ru/", wsdlLocation = "file:/home/itiu/work/ba2onto/src/main/wsdl/SearchService.wsdl")
public class SearchService
    extends Service
{

    private final static URL SEARCHSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(magnetico.ws.search.SearchService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = magnetico.ws.search.SearchService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/itiu/work/ba2onto/src/main/wsdl/SearchService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/itiu/work/ba2onto/src/main/wsdl/SearchService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SEARCHSERVICE_WSDL_LOCATION = url;
    }

    public SearchService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SearchService() {
        super(SEARCHSERVICE_WSDL_LOCATION, new QName("http://search.bigarchive.magnetosoft.ru/", "SearchService"));
    }

    /**
     * 
     * @return
     *     returns SearchEndpoint
     */
    @WebEndpoint(name = "SearchServiceEndpointPort")
    public SearchEndpoint getSearchServiceEndpointPort() {
        return super.getPort(new QName("http://search.bigarchive.magnetosoft.ru/", "SearchServiceEndpointPort"), SearchEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SearchEndpoint
     */
    @WebEndpoint(name = "SearchServiceEndpointPort")
    public SearchEndpoint getSearchServiceEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://search.bigarchive.magnetosoft.ru/", "SearchServiceEndpointPort"), SearchEndpoint.class, features);
    }

}
